# Minimal GitHub Actions CI Example for ODAVL Guardian
# Fails pipeline on DO_NOT_LAUNCH, passes on READY, configurable for FRICTION

name: Guardian Reality Gate
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  guardian-reality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Run Guardian in reality mode
        run: |
          node bin/guardian.js reality --url ${{ secrets.GUARDIAN_TARGET_URL }}
        id: guardian
      - name: Gate on Guardian verdict
        run: |
          status=$?
          if [ $status -eq 2 ]; then
            echo "Guardian verdict: DO_NOT_LAUNCH. Failing pipeline."
            exit 1
          elif [ $status -eq 1 ]; then
            echo "Guardian verdict: FRICTION. (Set GUARDIAN_ALLOW_FRICTION=true to allow)"
            if [ "$GUARDIAN_ALLOW_FRICTION" != "true" ]; then
              exit 1
            fi
          else
            echo "Guardian verdict: READY. Proceeding."
          fi
