name: 'VERAX CI (Pilot)'
description: 'Run VERAX in CI and upload a bundle of artifacts'
author: 'odavlstudio'

inputs:
  url:
    description: 'Target URL to scan'
    required: true
  src:
    description: 'Source directory (optional; VERAX will attempt auto-discovery if omitted)'
    required: false
    default: ''
  out:
    description: 'Output directory for artifacts'
    required: false
    default: ''
  min_coverage:
    description: 'Minimum coverage threshold (0-1)'
    required: false
    default: '0.90'
  ci_mode:
    description: 'CI mode: balanced or strict'
    required: false
    default: 'strict'
  fail_on_incomplete:
    description: 'Treat INCOMPLETE runs (exit 30) as failure'
    required: false
    default: 'true'
  upload_artifacts:
    description: 'Upload bundled VERAX artifacts'
    required: false
    default: 'true'

outputs:
  exit_code:
    description: 'VERAX exit code (0=SUCCESS, 20=FINDINGS, 30=INCOMPLETE, 50=INVARIANT_VIOLATION, 64=USAGE_ERROR)'
    value: ${{ steps.run_verax.outputs.exit_code }}
  run_dir:
    description: 'Resolved run directory path (best-effort)'
    value: ${{ steps.run_verax.outputs.run_dir }}
  bundle_dir:
    description: 'Bundle directory path'
    value: ${{ steps.run_verax.outputs.bundle_dir }}
  out_dir:
    description: 'Resolved output directory path'
    value: ${{ steps.run_verax.outputs.out_dir }}

runs:
  using: 'composite'
  steps:
    - name: Run VERAX
      id: run_verax
      shell: bash
      run: |
        set +e  # Don't exit on error, we need to capture exit code

        OUT="${{ inputs.out }}"
        if [ -z "$OUT" ]; then
          OUT="${RUNNER_TEMP:-/tmp}/verax"
        fi
        BUNDLE_DIR="$OUT/artifact-bundle"

        CMD="npx verax run --url ${{ inputs.url }} --out $OUT --min-coverage ${{ inputs.min_coverage }} --ci-mode ${{ inputs.ci_mode }}"
        if [ -n "${{ inputs.src }}" ]; then
          CMD="$CMD --src ${{ inputs.src }}"
        fi

        eval $CMD
        VERAX_EXIT_CODE=$?

        echo "exit_code=$VERAX_EXIT_CODE" >> $GITHUB_OUTPUT
        echo "out_dir=$OUT" >> $GITHUB_OUTPUT

        # Resolve latest run directory (best-effort)
        RUN_DIR=$(node --input-type=module -e "import { findLatestRun } from './node_modules/@veraxhq/verax/src/cli/util/ci/artifact-pack.js'; console.log(findLatestRun('$OUT/runs') || '')" 2>/dev/null)
        echo "run_dir=$RUN_DIR" >> $GITHUB_OUTPUT
        echo "bundle_dir=$BUNDLE_DIR" >> $GITHUB_OUTPUT

        # Handle exit codes
        case $VERAX_EXIT_CODE in
          0)
            echo "VERAX complete (exit 0)"
            ;;
          20)
            echo "VERAX findings (exit 20)"
            exit 20
            ;;
          30)
            if [ "${{ inputs.fail_on_incomplete }}" == "true" ]; then
              echo "VERAX incomplete (exit 30)"
              exit 30
            else
              echo "VERAX incomplete (exit 30) treated as warning"
              exit 0
            fi
            ;;
          50 | 64)
            echo "VERAX error (exit $VERAX_EXIT_CODE)"
            exit $VERAX_EXIT_CODE
            ;;
          *)
            echo "VERAX unexpected exit code: $VERAX_EXIT_CODE"
            exit $VERAX_EXIT_CODE
            ;;
        esac

    - name: Pack Artifacts
      if: inputs.upload_artifacts == 'true' && always()
      shell: bash
      run: |
        OUT="${{ steps.run_verax.outputs.out_dir }}"
        BUNDLE_DIR="${{ steps.run_verax.outputs.bundle_dir }}"
        RUN_DIR=$(node --input-type=module -e "import { findLatestRun } from './node_modules/@veraxhq/verax/src/cli/util/ci/artifact-pack.js'; console.log(findLatestRun('$OUT/runs') || '')" 2>/dev/null)
        if [ -n "$RUN_DIR" ]; then
          npx verax bundle "$RUN_DIR" "$BUNDLE_DIR"
        fi

    - name: Upload VERAX Artifacts
      if: inputs.upload_artifacts == 'true' && always()
      uses: actions/upload-artifact@v4
      with:
        name: verax-analysis
        path: ${{ steps.run_verax.outputs.bundle_dir }}/
        retention-days: 30
        if-no-files-found: ignore
